version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"     # TCP-клиенты (paho-mqtt, т.д.)
      - "9001:9001"     # WebSocket-клиенты (по желанию)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
