from abc import ABC, abstractmethod

class AEngine(ABC):
    @abstractmethod
    def forward(self, ms: int = 0) -> None: ...
    @abstractmethod
    def left(self, ms: int = 0) -> None: ...
    @abstractmethod
    def right(self, ms: int = 0) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
